# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee67719a1c4d2e0d9872fcb272135446e20282a4d25da662106fe0d5ad6380040c0deadd91e99c4a33c288839f412145475fe2a8a958e8f57d33d0f9fe88cf9f

test:
  secret_key_base: b2f7c52fda8b6f484095dd5c3bf30bbad44a124970dc3d8de3e6c89a5160f4dcf25d96f2b5565c1675536743f63ca7834fedb8b20e3ed2a9514dd0a8ba9fb2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
